Web/CeroFilas.Web/Areas/Administration/Controllers/BlogPostsController.cs
namespace CeroFilas.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using CeroFilas.Common;
    using CeroFilas.Services.Cloudinary;
    using CeroFilas.Services.Data.BlogPosts;
    using CeroFilas.Web.ViewModels.BlogPosts;
    using Microsoft.AspNetCore.Mvc;

    public class BlogPostsController : AdministrationController
    {
        private readonly IBlogPostsService blogPostsService;
        private readonly ICloudinaryService cloudinaryService;

        public BlogPostsController(
            IBlogPostsService blogPostsService,
            ICloudinaryService cloudinaryService)
        {
            this.blogPostsService = blogPostsService;
            this.cloudinaryService = cloudinaryService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new BlogPostsListViewModel
            {
                BlogPosts = await this.blogPostsService.GetAllAsync<BlogPostViewModel>(),
            };
            return this.View(viewModel);
        }

        public IActionResult AddBlogPost()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddBlogPost(BlogPostInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            string imageUrl;
            try
            {
                imageUrl = await this.cloudinaryService.UploadPictureAsync(input.Image, input.Title);
            }
            catch (System.Exception)
            {
                // In case of missing Cloudinary configuration from appsettings.json
                imageUrl = GlobalConstants.Images.DemoImg;
            }

            await this.blogPostsService.AddAsync(input.Title, input.Content, input.Author, imageUrl);
            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteBlogPost(int id)
        {
            await this.blogPostsService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

Web/CeroFilas.Web/Controllers/BlogPostsController.cs
namespace CeroFilas.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CeroFilas.Services.Data.BlogPosts;
    using CeroFilas.Web.ViewModels.BlogPosts;
    using CeroFilas.Web.ViewModels.Common.Pagination;
    using Microsoft.AspNetCore.Mvc;

    public class BlogPostsController : BaseController
    {
        private readonly IBlogPostsService blogPostsService;

        public BlogPostsController(IBlogPostsService blogPostsService)
        {
            this.blogPostsService = blogPostsService;
        }

        public async Task<IActionResult> Index(
            int? sortId,
            int? pageNumber) // blogPostId
        {
            if (sortId != null)
            {
                var blogPost = await this.blogPostsService
                    .GetByIdAsync<BlogPostViewModel>(sortId.Value);
                if (blogPost == null)
                {
                    return new StatusCodeResult(404);
                }
            }

            this.ViewData["CurrentSort"] = sortId;

            int pageSize = PageSizesConstants.BlogPosts;
            var pageIndex = pageNumber ?? 1;

            var blogPosts = await this.blogPostsService
                .GetAllWithPagingAsync<BlogPostViewModel>(sortId, pageSize, pageIndex);
            var blogPostsList = blogPosts.ToList();

            var count = await this.blogPostsService.GetCountForPaginationAsync();

            var viewModel = new BlogPostsPaginatedListViewModel
            {
                BlogPosts = new PaginatedList<BlogPostViewModel>(blogPostsList, count, pageIndex, pageSize),
            };

            return this.View(viewModel);
        }
    }
}

Web/CeroFilas.Web/Views/BlogPosts/Index.cshtml
@model CeroFilas.Web.ViewModels.BlogPosts.BlogPostsPaginatedListViewModel
@{
    this.ViewData["Title"] = "Blog";
}

<div class="row">
    <!-- News Posts -->
    <div class="col-lg-8">
        <div class="news_posts">
            @foreach (var blogPost in Model.BlogPosts)
            {
                <hr class="bg-dark mx-4" style="height: 6px;" />

                <!-- News Post -->
                <div class="news_post">
                    <div class="news_post_image"><img src="@blogPost.ImageUrl" alt=""></div>
                    <div class="news_post_content">
                        <div class="news_post_title">
                            <a asp-area="" asp-controller="BlogPosts" asp-action="Details" asp-route-id="@blogPost.Id">@blogPost.Title</a>
                        </div>
                        <div class="news_post_info">
                            <ul class="d-flex flex-row align-items-center justify-content-start">
                                <li>
                                    <a asp-area="" asp-controller="BlogPosts" asp-action="Details" asp-route-id="@blogPost.Id">by @blogPost.Author</a>
                                </li>
                                <li>
                                    <a asp-area="" asp-controller="BlogPosts" asp-action="Details" asp-route-id="@blogPost.Id">@blogPost.CreatedOn.Date.ToString("D")</a>
                                </li>
                            </ul>
                        </div>
                        <div class="news_post_text">
                            <p>@blogPost.Content</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

    <!-- Sidebar -->
    <div class="col-lg-4">
        <div class="news_sidebar">
            <!-- Latest News -->
            <div class="sidebar_latest">
                <div class="sidebar_title">Latest Blog Posts</div>
                <div class="sidebar_latest_container">
                    <div>
                        @await Component.InvokeAsync("LatestBlogPosts", 10)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.BlogPosts.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.BlogPosts.HasNextPage ? "disabled" : "";
}

@if (ViewData["CurrentSort"] == null)
{
    <div class="row ml-5">
        <div class="m-5">
            <a asp-action="Index"
               asp-route-pageNumber="@(Model.BlogPosts.PageIndex - 1)"
               style="color: #BA55D3" class="btn btn-outline-secondary btn-lg @prevDisabled">
                <i class="fa fa-arrow-left"></i>
            </a>
        </div>
        <div class="m-5">
            <a asp-action="Index"
               asp-route-pageNumber="@(Model.BlogPosts.PageIndex + 1)"
               style="color: #BA55D3" class="btn btn-outline-secondary btn-lg @nextDisabled">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
    </div>
}