Web/CeroFilas.Web/Areas/Manager/Controllers/DashboardController.cs
namespace CeroFilas.Web.Areas.Manager.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Text;
    using System.Text.Encodings.Web;

    using CeroFilas.Data.Models;
    using CeroFilas.Services.Data.Partners;
    using Microsoft.AspNetCore.Mvc;
    using CeroFilas.Web.ViewModels.Partners;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Identity.UI.Services;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class DashboardController : ManagerBaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPartnersService PartnersService;

        public DashboardController(
            UserManager<ApplicationUser> userManager,
            IPartnersService PartnersService)
        {
            this.userManager = userManager;
            this.PartnersService = PartnersService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var userId = await this.userManager.GetUserIdAsync(user);

            var viewModel = new PartnersListViewModel
            {
                Partners = await this.PartnersService.GetAllByOwnerAsync<PartnerViewModel>(userId),
            };
            return this.View(viewModel);
        }
    }
}

Web/CeroFilas.Web/Controllers/AppointmentsController.cs
namespace CeroFilas.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using System.Text;
    using System.Text.Encodings.Web;

    using CeroFilas.Data.Models;
    using CeroFilas.Services.Data.Appointments;
    using CeroFilas.Services.Data.Partners;
    using CeroFilas.Services.Data.PartnerServicesServices;
    using CeroFilas.Services.DateTimeParser;
    using CeroFilas.Web.ViewModels.Appointments;
    using CeroFilas.Web.ViewModels.PartnerServices;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Identity.UI.Services;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class AppointmentsController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDateTimeParserService dateTimeParserService;
        private readonly IPartnersService PartnersService;
        private readonly IAppointmentsService appointmentsService;
        private readonly IPartnerServicesService PartnerServicesService;
        private readonly IEmailSender emailSender;

        public AppointmentsController(
            UserManager<ApplicationUser> userManager,
            IAppointmentsService appointmentsService,
            IPartnerServicesService PartnerServicesService,
            IDateTimeParserService dateTimeParserService,
            IPartnersService PartnersService,
            IEmailSender emailSender)
        {
            this.userManager = userManager;
            this.appointmentsService = appointmentsService;
            this.PartnerServicesService = PartnerServicesService;
            this.dateTimeParserService = dateTimeParserService;
            this.PartnersService = PartnersService;
            this.emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var userId = await this.userManager.GetUserIdAsync(user);

            var viewModel = new AppointmentsListViewModel
            {
                Appointments =
                    await this.appointmentsService.GetUpcomingByUserAsync<AppointmentViewModel>(userId),
            };
            return this.View(viewModel);
        }

        public async Task<IActionResult> MakeAnAppointment(string PartnerId, int serviceId)
        {
            var PartnerService = await this.PartnerServicesService.GetByIdAsync<PartnerServiceSimpleViewModel>(PartnerId, serviceId);
            if (PartnerService == null || !PartnerService.Available)
            {
                return this.View("UnavailableService");
            }

            var viewModel = new AppointmentInputModel
            {
                PartnerId = PartnerId,
                ServiceId = serviceId,
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> MakeAnAppointment(AppointmentInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("MakeAnAppointment", new { input.PartnerId, input.ServiceId });
            }

            DateTime dateTime;
            try
            {
                dateTime = this.dateTimeParserService.ConvertStrings(input.Date, input.Time);
            }
            catch (System.Exception)
            {
                return this.RedirectToAction("MakeAnAppointment", new { input.PartnerId, input.ServiceId });
            }

            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var userId = await this.userManager.GetUserIdAsync(user);

            await this.appointmentsService.AddAsync(userId, input.PartnerId, input.ServiceId, dateTime);

            var callbackUrl = Url.Page("/Appoinments");

            // Send Email 
            var uemail = user?.Email;
            await this.emailSender.SendEmailAsync(
                uemail,
                "Cita Agendada",
                $"Haz agendado una cita exitosamente para el día {dateTime}, puedes ver los demás detalles haciendo <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>click aquí</a>.");

            return this.RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> CancelAppointment(string id)
        {
            var viewModel = await this.appointmentsService.GetByIdAsync<AppointmentViewModel>(id);

            if (viewModel == null)
            {
                return new StatusCodeResult(404);
            }

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAppointment(string id)
        {
            await this.appointmentsService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

Web/CeroFilas.Web/Controllers/CategoriesController.cs
namespace CeroFilas.Web.Controllers
{
    using System.Threading.Tasks;

    using CeroFilas.Services.Data.Categories;
    using CeroFilas.Web.ViewModels.Categories;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : BaseController
    {
        private readonly ICategoriesService categoriesService;

        public CategoriesController(ICategoriesService categoriesService)
        {
            this.categoriesService = categoriesService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new CategoriesListViewModel
            {
                Categories = await this.categoriesService.GetAllAsync<CategoryViewModel>(),
            };
            return this.View(viewModel);
        }
    }
}

Web/CeroFilas.Web/Controllers/PartnersController.cs
namespace CeroFilas.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using CeroFilas.Services.Data.Categories;
    using CeroFilas.Services.Data.Partners;
    using CeroFilas.Web.ViewModels.Categories;
    using CeroFilas.Web.ViewModels.Common.Pagination;
    using CeroFilas.Web.ViewModels.Partners;
    using Microsoft.AspNetCore.Mvc;

    public class PartnersController : BaseController
    {
        private readonly IPartnersService partnersService;
        private readonly ICategoriesService categoriesService;

        public PartnersController(
            IPartnersService partnersService,
            ICategoriesService categoriesService)
        {
            this.partnersService = partnersService;
            this.categoriesService = categoriesService;
        }

        public async Task<IActionResult> Index(
            int? sortId, // categoryId
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            if (sortId != null)
            {
                var category = await this.categoriesService
                    .GetByIdAsync<CategorySimpleViewModel>(sortId.Value);
                if (category == null)
                {
                    return new StatusCodeResult(404);
                }

                this.ViewData["CategoryName"] = category.Name;
            }

            this.ViewData["CurrentSort"] = sortId;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            this.ViewData["CurrentFilter"] = searchString;

            int pageSize = PageSizesConstants.Partners;
            var pageIndex = pageNumber ?? 1;

            var partners = await this.partnersService
                .GetAllWithSortingFilteringAndPagingAsync<PartnerViewModel>(
                    searchString, sortId,pageSize, pageIndex);
            var partnersList = partners.ToList();

            var count = await this.partnersService
                .GetCountForPaginationAsync(searchString, sortId);

            var viewModel = new PartnersPaginatedListViewModel
            {
                Partners = new PaginatedList<PartnerViewModel>(partnersList, count, pageIndex, pageSize),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(string id)
        {
            var viewModel = await this.partnersService.GetByIdAsync<PartnerWithServicesViewModel>(id);

            if (viewModel == null)
            {
                return new StatusCodeResult(404);
            }

            return this.View(viewModel);
        }
    }
}

Web/CeroFilas.Web/Areas/Administration/Views/Shared/_AdminLayout.cshtml
@using CeroFilas.Common
<!DOCTYPE html>
<html lang="es_CO">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/aos/dist/aos.css" rel="stylesheet">
        <link href="~/lib/glightbox/dist/css/glightbox.min.css" rel="stylesheet">
        <link href="~/plugins/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="~/plugins/remixicon/remixicon.css" rel="stylesheet">
        <link href="~/css/style.css" rel="stylesheet">
    </environment>
    <environment names="Staging,Production">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/lib/aos/dist/aos.css" rel="stylesheet">
        <link href="~/lib/glightbox/dist/css/glightbox.min.css" rel="stylesheet">
        <link href="~/plugins/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="~/plugins/remixicon/remixicon.css" rel="stylesheet">
        <link href="~/css/style.min.css" rel="stylesheet">
    </environment>
    @this.RenderSection("Styles", required: false)
</head>

<body>
    <partial name="_CookieConsentPartial" />

    <!-- ======= Header ======= -->
    <partial name="_MenuPartial" />

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
        <div class="container" data-aos="fade-bottom">

            <ol>
                <li><a href="/">Inicio</a></li>
                <li>Adminitración</li>
                <li>@this.ViewData["Title"].ToString()</li>
            </ol>
            <h2>@this.ViewData["Title"].ToString()</h2>

        </div>
    </section><!-- End Breadcrumbs -->
    <main id="main">
        <section class='@this.ViewData["cClass"]?.ToString()'>
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-3">
                    <partial name="_AdminSidebarPartial"></partial>
                    </div>
                    <div class="col-lg-9">
                        @this.RenderBody()
                    </div>
                </div>
            </div>
        </section>
    </main><!-- End #main -->


    <!-- ======= Footer ======= -->
    <partial name="_FooterPartial" />
    <!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- plugins JS Files -->
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
            asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/aos/dist/aos.js"></script>
        <script src="~/lib/isotope-layout/dist/isotope.pkgd.min.js"></script>
        <script src="~/lib/glightbox/dist/js/glightbox.min.js"></script>
        <script src="~/plugins/purecounter/purecounter.js"></script>

        <!-- Template Main JS File -->
        <script src="~/js/main.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"
            asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/aos/dist/aos.js"></script>
        <script src="~/lib/isotope-layout/dist/isotope.pkgd.min.js"></script>
        <script src="~/lib/glightbox/dist/js/glightbox.min.js"></script>
        <script src="~/plugins/purecounter/purecounter.js"></script>

        <!-- Template Main JS File -->
        <script src="~/js/main.min.js"></script>
    </environment>
    @this.RenderSection("Scripts", required: false)
</body>

</html>

Web/CeroFilas.Web/Areas/Administration/Views/Shared/_AdminSidebarPartial.cshtml
<!-- Sidebar -->
<div class="bg-light border border-secondary" id="sidebar-wrapper">
    <div class="list-group list-group-flush">

        <a asp-area="Administration" asp-controller="Dashboard" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Inicio</a>

        <a asp-area="Administration" asp-controller="Categories" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Categorias</a>

        <a asp-area="Administration" asp-controller="Services" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Servicios</a>

        <a asp-area="Administration" asp-controller="Cities" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Ciudades</a>

        <a asp-area="Administration" asp-controller="Partners" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Empresas</a>

        <a asp-area="Administration" asp-controller="Appointments" asp-action="Index"
           class="list-group-item list-group-item-action bg-light">Citas</a>

    </div>
</div>
<!-- /#sidebar-wrapper -->