Web/CeroFilas.Web/Areas/Administration/Controllers/CitiesController.cs
namespace CeroFilas.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using CeroFilas.Common;
    using CeroFilas.Services.Data.Cities;
    using CeroFilas.Web.ViewModels.Cities;
    using Microsoft.AspNetCore.Mvc;

    public class CitiesController : AdministrationController
    {
        private readonly ICitiesService citiesService;

        public CitiesController(ICitiesService citiesService)
        {
            this.citiesService = citiesService;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new CitiesListViewModel
            {
                Cities = await this.citiesService.GetAllAsync<CityViewModel>(),
            };
            return this.View(viewModel);
        }

        public IActionResult AddCity()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCity(CityInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.citiesService.AddAsync(input.Name);

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCity(int id)
        {
            await this.citiesService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

Web/CeroFilas.Web/Areas/Administration/Views/Cities/AddCity.cshtml
@model CeroFilas.Web.ViewModels.Cities.CityInputModel
@{
    this.ViewData["Title"] = "Añadir Ciudad";
}

<div class="col-lg-6">
    <h2>Añadir Nueva Ciudad</h2>
    <form method="post" enctype="multipart/form-data" class="pt-4">
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">MNombre</label>
            <div class="col-sm-8">
                <input type="text" asp-for="@Model.Name" class="form-control" required="required">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-6 text-right">
                <button type="submit" class="btn btn-success"
                        asp-area="Administration" asp-controller="Cities" asp-action="AddCity">
                    Añadir Ciudad
                </button>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-danger" asp-area="Administration" asp-controller="Cities" asp-action="Index">Cancelar</a>
            </div>
        </div>
    </form>
</div>

Web/CeroFilas.Web/Areas/Administration/Views/Cities/Index.cshtml
@model CeroFilas.Web.ViewModels.Cities.CitiesListViewModel
@using CeroFilas.Common
@{
    this.ViewData["Title"] = "Ciudades";
}

<h2>
    Todas las Ciudades (@Model.Cities.Count())
    <span>
        <a class="btn btn-info" asp-area="Administration" asp-controller="Cities" asp-action="AddCity">Añadir Nueva
            Ciudad</a>
    </span>
</h2>

<table class="table table-bordered table-striped">
    <thead class="thead-light">
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Empresas</th>
            <th scope="col">Opciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var city in this.Model.Cities)
        {
            <tr>
                <th scope="row">@city.Name</th>
                <td>@city.PartnersCount</td>
                <td>
                    <form method="post">
                        <button type="submit" class="btn btn-danger btn-sm" asp-area="Administration"
                        asp-controller="Cities" asp-action="DeleteCity" asp-route-id="@city.Id">
                            Borrar
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>